services:
  # 1. The Python Web Service
  - type: web
    name: ecom-app
    runtime: python
    region: singapore
    plan: free
    
    # Commands to build your app
    buildCommand: |
      pip install -r requirements.txt
    
    # Command to start your app
    startCommand: gunicorn run:app

    # Link to the database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecom-database
          property: internalDatabaseUrl
      - key: FLASK_APP
        value: app
      
  # 2. The PostgreSQL Database
  - type: psql
    name: ecom-database
    region: singapore
    plan: free
