services:
  # 1. The Python Web Service
  - type: web
    name: ecom-app
    runtime: python
    region: singapore  # You can change this to 'oregon', 'frankfurt', etc.
    plan: free         # Use the free tier
    
    # Commands to build your app
    buildCommand: |
      pip install -r requirements.txt
    
    # Command to start your app
    # It runs gunicorn, points it to your 'run.py' file, and finds 'app'
    startCommand: gunicorn run:app

    # Link to the database
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecom-database # Must match the database name below
          property: internalDatabaseUrl
      - key: FLASK_APP # Lets you run 'flask' commands in the shell
        value: app
      - key: DB_PASSWORD # Your local MySQL password (won't be used, but good to have)
        sync: false 
        
  # 2. The PostgreSQL Database
  - type: psql
    name: ecom-database
    region: singapore  # Use the same region as your app
    plan: free         # Use the free database tier
