services:
  # 1. The Python Web Service (Your Flask App)
  - type: web
    name: ecom-recommender
    runtime: python
    region: singapore # Choose the region closest to your Neon database (e.g., oregon, frankfurt)
    plan: free     # Use the free tier
    
    # Commands to build your app
    buildCommand: |
      pip install -r requirements.txt
    
    # Command to start your production server
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app

    # Environment Variables
    envVars:
      - key: FLASK_APP
        value: app
      
